# Site settings
title: Nice Blog
name: ynwa # your name
email: ynwa_wang@foxmail.com # your email address
description: >
    A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ynwawang.github.io" # the base hostname & protocol for your site
twitter_username: ynwawang # your Twitter username
github_username: ynwawang # your Github username


google-analytics: UA-75034651-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
